/**
 * Industry-specific dashboard configurations.
 * Each industry defines: theme, KPIs, charts, filters, AI prompt context, icons, etc.
 */

export const INDUSTRY_CONFIGS = {
  retail: {
    label: 'Retail Analytics',
    emoji: '🛍️',
    theme: {
      primary:   '#6366f1',
      secondary: '#8b5cf6',
      accent:    '#06b6d4',
      bg:        'linear-gradient(135deg,rgba(99,102,241,0.12),rgba(139,92,246,0.06))',
      glow:      'rgba(99,102,241,0.3)',
    },
    kpis: [
      { key:'revenue',    label:'Total Revenue',   icon:'💰', format:'currency', color:'#6366f1' },
      { key:'orders',     label:'Total Orders',    icon:'📦', format:'number',   color:'#8b5cf6' },
      { key:'customers',  label:'Customers',       icon:'👥', format:'number',   color:'#06b6d4' },
      { key:'aov',        label:'Avg Order Value', icon:'🛒', format:'currency', color:'#34d399' },
      { key:'margin',     label:'Profit Margin',   icon:'📈', format:'percent',  color:'#f59e0b' },
      { key:'growth',     label:'Growth Rate',     icon:'🚀', format:'percent',  color:'#f472b6' },
    ],
    charts: ['trend','category','topProducts','geo','frequency','heatmap'],
    filters: ['date','region','store','category','product','customerType'],
    aiContext: 'retail business analyzing sales, inventory, customer behavior, and revenue performance',
    insights: ['Best selling products','Low performing categories','Seasonal demand patterns','Customer buying behavior','High profit products'],
    recommendations: ['Restock recommendations','Discount suggestions','Marketing opportunities','Upselling strategies'],
    forecast: ['Next Month Revenue','Demand Forecast','Inventory Forecast'],
    color1: '#6366f1', color2: '#8b5cf6',
  },

  restaurant: {
    label: 'Restaurant Analytics',
    emoji: '🍽️',
    theme: {
      primary:   '#f97316',
      secondary: '#ef4444',
      accent:    '#fbbf24',
      bg:        'linear-gradient(135deg,rgba(249,115,22,0.12),rgba(239,68,68,0.06))',
      glow:      'rgba(249,115,22,0.3)',
    },
    kpis: [
      { key:'daily_revenue',  label:'Daily Revenue',    icon:'💵', format:'currency', color:'#f97316' },
      { key:'orders',         label:'Total Orders',     icon:'🍕', format:'number',   color:'#ef4444' },
      { key:'avg_bill',       label:'Average Bill',     icon:'🧾', format:'currency', color:'#fbbf24' },
      { key:'customers',      label:'Customer Count',   icon:'🪑', format:'number',   color:'#34d399' },
      { key:'occupancy',      label:'Table Occupancy',  icon:'🪑', format:'percent',  color:'#8b5cf6' },
      { key:'food_cost',      label:'Food Cost %',      icon:'🥗', format:'percent',  color:'#06b6d4' },
    ],
    charts: ['hourly','menuItems','revenueCategory','peakHours','staffPerformance','ratings'],
    filters: ['date','branch','waiter','foodCategory','paymentMethod'],
    aiContext: 'restaurant business analyzing food sales, table occupancy, peak hours, menu performance, and customer satisfaction',
    insights: ['Best selling dishes','Least ordered items','Busiest days & peak hours','High profit dishes','Customer preferences'],
    recommendations: ['Stock popular ingredients','Combo offer suggestions','Menu optimization','Reduce food wastage'],
    forecast: ['Customer Traffic','Ingredient Requirements','Weekend Revenue'],
    color1: '#f97316', color2: '#ef4444',
  },

  healthcare: {
    label: 'Healthcare Analytics',
    emoji: '🏥',
    theme: {
      primary:   '#0ea5e9',
      secondary: '#06b6d4',
      accent:    '#34d399',
      bg:        'linear-gradient(135deg,rgba(14,165,233,0.12),rgba(6,182,212,0.06))',
      glow:      'rgba(14,165,233,0.3)',
    },
    kpis: [
      { key:'patients',    label:'Total Patients',   icon:'👤', format:'number',  color:'#0ea5e9' },
      { key:'admissions',  label:'Admissions',       icon:'🏥', format:'number',  color:'#06b6d4' },
      { key:'discharges',  label:'Discharges',       icon:'✅', format:'number',  color:'#34d399' },
      { key:'emergency',   label:'Emergency Cases',  icon:'🚨', format:'number',  color:'#ef4444' },
      { key:'avg_stay',    label:'Avg Stay (days)',   icon:'📅', format:'decimal', color:'#8b5cf6' },
      { key:'bed_occ',     label:'Bed Occupancy',    icon:'🛏️', format:'percent', color:'#f59e0b' },
    ],
    charts: ['admissionTrend','diseaseDistribution','ageDistribution','departmentPerf','doctorWorkload','recoveryRate'],
    filters: ['department','doctor','disease','gender','age','date'],
    aiContext: 'healthcare facility analyzing patient admissions, disease patterns, department performance, and medical resource utilization',
    insights: ['Most common diseases','High risk patients','Department overload','Peak admission times','Bed availability trends'],
    recommendations: ['Increase staffing in overloaded depts','Restock critical medicines','Optimize doctor schedules','Prevent overcrowding'],
    forecast: ['Patient Forecast','Medicine Demand','Bed Requirements','Doctor Requirements'],
    color1: '#0ea5e9', color2: '#06b6d4',
  },

  manufacturing: {
    label: 'Manufacturing Analytics',
    emoji: '🏭',
    theme: {
      primary:   '#64748b',
      secondary: '#475569',
      accent:    '#06b6d4',
      bg:        'linear-gradient(135deg,rgba(100,116,139,0.12),rgba(6,182,212,0.06))',
      glow:      'rgba(100,116,139,0.3)',
    },
    kpis: [
      { key:'production',  label:'Production Vol.',  icon:'⚙️', format:'number',  color:'#64748b' },
      { key:'utilization', label:'Machine Util.',    icon:'🏭', format:'percent', color:'#06b6d4' },
      { key:'defect_rate', label:'Defect Rate',      icon:'⚠️', format:'percent', color:'#ef4444' },
      { key:'downtime',    label:'Downtime (hrs)',   icon:'⏱️', format:'decimal', color:'#f59e0b' },
      { key:'cost',        label:'Production Cost',  icon:'💲', format:'currency',color:'#8b5cf6' },
      { key:'efficiency',  label:'Efficiency',       icon:'📊', format:'percent', color:'#34d399' },
    ],
    charts: ['productionTrend','machinePerf','qualityDefects','downtimeTimeline','energyConsumption','inventoryLevel'],
    filters: ['plant','machine','shift','operator','date'],
    aiContext: 'manufacturing plant analyzing production volume, machine performance, quality defects, downtime, and operational efficiency',
    insights: ['Production bottlenecks','High defect machines','Production delays','Material shortages','Efficiency opportunities'],
    recommendations: ['Preventive maintenance schedule','Optimize production flow','Reduce material wastage','Improve shift efficiency'],
    forecast: ['Production Forecast','Demand Prediction','Maintenance Schedule','Inventory Forecast'],
    color1: '#64748b', color2: '#06b6d4',
  },

  education: {
    label: 'Education Analytics',
    emoji: '🎓',
    theme: {
      primary:   '#8b5cf6',
      secondary: '#a78bfa',
      accent:    '#34d399',
      bg:        'linear-gradient(135deg,rgba(139,92,246,0.12),rgba(52,211,153,0.06))',
      glow:      'rgba(139,92,246,0.3)',
    },
    kpis: [
      { key:'students',    label:'Total Students',   icon:'🎒', format:'number',  color:'#8b5cf6' },
      { key:'attendance',  label:'Attendance',       icon:'✅', format:'percent', color:'#34d399' },
      { key:'pass_rate',   label:'Pass Rate',        icon:'📝', format:'percent', color:'#06b6d4' },
      { key:'assignments', label:'Assignments Done', icon:'📚', format:'number',  color:'#f59e0b' },
      { key:'avg_marks',   label:'Average Marks',    icon:'⭐', format:'decimal', color:'#f472b6' },
      { key:'completion',  label:'Course Completion',icon:'🏆', format:'percent', color:'#a78bfa' },
    ],
    charts: ['attendanceTrend','subjectPerformance','gradeDistribution','topStudents','teacherPerformance','coursePopularity'],
    filters: ['class','section','teacher','subject','semester','gender'],
    aiContext: 'educational institution analyzing student performance, attendance, subject outcomes, and learning progress',
    insights: ['Students at risk of failing','Best performing subjects','Attendance issues','Learning progress trends','Teacher effectiveness'],
    recommendations: ['Schedule extra classes for weak students','Identify and support at-risk students','Improve attendance tracking','Suggest personalized study plans'],
    forecast: ['Performance Prediction','Dropout Risk','Admission Forecast'],
    color1: '#8b5cf6', color2: '#34d399',
  },

  marketing: {
    label: 'Marketing Analytics',
    emoji: '📢',
    theme: {
      primary:   '#f472b6',
      secondary: '#ec4899',
      accent:    '#fbbf24',
      bg:        'linear-gradient(135deg,rgba(244,114,182,0.12),rgba(251,191,36,0.06))',
      glow:      'rgba(244,114,182,0.3)',
    },
    kpis: [
      { key:'revenue',    label:'Campaign Revenue', icon:'💰', format:'currency', color:'#f472b6' },
      { key:'leads',      label:'Total Leads',      icon:'🎯', format:'number',   color:'#ec4899' },
      { key:'conversions',label:'Conversions',      icon:'✅', format:'number',   color:'#34d399' },
      { key:'ctr',        label:'CTR',              icon:'👆', format:'percent',  color:'#fbbf24' },
      { key:'roas',       label:'ROAS',             icon:'📈', format:'decimal',  color:'#8b5cf6' },
      { key:'spend',      label:'Marketing Spend',  icon:'💸', format:'currency', color:'#06b6d4' },
    ],
    charts: ['campaignPerf','trafficSources','conversionFunnel','leadSources','socialMedia','roiTrend'],
    filters: ['campaign','platform','region','age','gender','date'],
    aiContext: 'marketing team analyzing campaign performance, lead generation, conversion rates, ROI, and audience engagement across channels',
    insights: ['Best performing campaigns','Worst performing campaigns','High converting channels','Customer segmentation insights','Budget efficiency'],
    recommendations: ['Scale winning campaigns','Pause poor performers','Improve email timing & targeting','Focus budget on high-ROI channels'],
    forecast: ['Future Leads','Campaign Performance','Sales Forecast','Budget Optimization'],
    color1: '#f472b6', color2: '#fbbf24',
  },

  finance: {
    label: 'Finance Analytics',
    emoji: '💹',
    theme: {
      primary:   '#34d399',
      secondary: '#10b981',
      accent:    '#06b6d4',
      bg:        'linear-gradient(135deg,rgba(52,211,153,0.12),rgba(6,182,212,0.06))',
      glow:      'rgba(52,211,153,0.3)',
    },
    kpis: [
      { key:'revenue',    label:'Revenue',        icon:'💰', format:'currency', color:'#34d399' },
      { key:'profit',     label:'Net Profit',     icon:'📈', format:'currency', color:'#10b981' },
      { key:'expenses',   label:'Expenses',       icon:'💸', format:'currency', color:'#ef4444' },
      { key:'cash_flow',  label:'Cash Flow',      icon:'💧', format:'currency', color:'#06b6d4' },
      { key:'net_income', label:'Net Income',     icon:'🏦', format:'currency', color:'#8b5cf6' },
      { key:'roi',        label:'ROI',            icon:'📊', format:'percent',  color:'#fbbf24' },
    ],
    charts: ['revenueTrend','expenseBreakdown','cashFlow','budgetVsActual','profitMargin','investmentPerf'],
    filters: ['department','date','expenseType','revenueSource','project'],
    aiContext: 'finance department analyzing revenue streams, expense patterns, cash flow, profitability, and investment performance',
    insights: ['High expense categories','Profit growth trends','Cash flow risks','Investment opportunities','Budget variance analysis'],
    recommendations: ['Reduce operational costs','Increase high-ROI investments','Improve cash flow management','Optimize budget allocation'],
    forecast: ['Revenue Forecast','Expense Forecast','Cash Flow Prediction','Profit Forecast'],
    color1: '#34d399', color2: '#06b6d4',
  },

  general: {
    label: 'General Analytics',
    emoji: '📊',
    theme: {
      primary:   '#6366f1',
      secondary: '#8b5cf6',
      accent:    '#06b6d4',
      bg:        'linear-gradient(135deg,rgba(99,102,241,0.1),rgba(139,92,246,0.05))',
      glow:      'rgba(99,102,241,0.25)',
    },
    kpis: [
      { key:'total',   label:'Total Records', icon:'📋', format:'number',  color:'#6366f1' },
      { key:'avg',     label:'Average Value', icon:'📊', format:'decimal', color:'#8b5cf6' },
      { key:'max',     label:'Peak Value',    icon:'🔝', format:'number',  color:'#34d399' },
      { key:'min',     label:'Min Value',     icon:'🔽', format:'number',  color:'#06b6d4' },
      { key:'growth',  label:'Trend',         icon:'📈', format:'percent', color:'#f59e0b' },
      { key:'anomaly', label:'Anomalies',     icon:'⚠️', format:'number',  color:'#ef4444' },
    ],
    charts: ['trend','category','distribution','scatter'],
    filters: ['date','category'],
    aiContext: 'business dataset with mixed data types requiring comprehensive analysis',
    insights: ['Key trends','Top performers','Outliers detected','Pattern analysis','Data quality notes'],
    recommendations: ['Focus on top performers','Investigate anomalies','Optimize underperformers','Monitor trends'],
    forecast: ['30-Day Forecast','Trend Prediction'],
    color1: '#6366f1', color2: '#8b5cf6',
  },
}

export const getIndustryConfig = (industry) =>
  INDUSTRY_CONFIGS[industry] || INDUSTRY_CONFIGS.general
